export const COMMUNITY_SPEND_REPORT_MINIMUM = 5;
export const COMMUNITY_NOTE_MAX_LENGTH = 500;
export const VISIT_TYPES = ['dine_in', 'pickup', 'delivery', 'activity', 'admission', 'other'] as const;
export type VisitType = typeof VISIT_TYPES[number];
export type VisitReportInput = { placeId: string; rating: number | null; totalSpendMinor: number | null; partySize: number | null; visitType: VisitType | null; visitDate: string; shortNote: string | null };

export function parsePesoToMinor(value: string): number | null { const normalized = value.trim().replace(/,/g, ''); if (!normalized) return null; if (!/^\d+(?:\.\d{1,2})?$/.test(normalized)) return Number.NaN; const [whole, fraction = ''] = normalized.split('.'); const minor = Number(whole) * 100 + Number((fraction + '00').slice(0, 2)); return Number.isSafeInteger(minor) ? minor : Number.NaN; }
export function formatPesoMinor(amount: number) { return `₱${(amount / 100).toLocaleString('en-PH', { minimumFractionDigits: amount % 100 ? 2 : 0, maximumFractionDigits: 2 })}`; }
export function spendPerPersonMinor(totalSpendMinor: number | null, partySize: number | null) { return totalSpendMinor !== null && partySize !== null && partySize > 0 ? Math.floor(totalSpendMinor / partySize) : null; }
export function validateVisitReport(input: VisitReportInput): string | null { if (input.rating !== null && (!Number.isInteger(input.rating) || input.rating < 1 || input.rating > 5)) return 'Choose a rating from 1 to 5.'; if (input.totalSpendMinor !== null && (!Number.isSafeInteger(input.totalSpendMinor) || input.totalSpendMinor < 0)) return 'Total spent must be a non-negative peso amount.'; if (input.totalSpendMinor !== null && (!Number.isInteger(input.partySize) || (input.partySize ?? 0) <= 0)) return 'Enter the number of people for this spend.'; if (input.totalSpendMinor === null && input.partySize !== null) return 'Add a total spent amount or clear the number of people.'; if (!/^\d{4}-\d{2}-\d{2}$/.test(input.visitDate)) return 'Enter a visit date as YYYY-MM-DD.'; if (input.visitDate > new Date().toISOString().slice(0, 10)) return 'Visit date cannot be in the future.'; if ((input.shortNote?.length ?? 0) > COMMUNITY_NOTE_MAX_LENGTH) return `Keep the note under ${COMMUNITY_NOTE_MAX_LENGTH} characters.`; if (input.rating === null && input.totalSpendMinor === null) return 'Add a rating, spending details, or both.'; return null; }
