import { mkdir, writeFile } from "node:fs/promises";
import { loadEnvFile } from "node:process";
import { fileURLToPath } from "node:url";
import { connectSupabaseLoaderDatabase } from "../database/supabase-loader-client.js";
import { PILOT_BRAND_IDENTITY_RULES, classifyChainIdentity, type ChainIdentityRule } from "../pricing/chain-pilot.js";

type BranchRow = Readonly<{ place_id: string; source_place_id: string; place_name: string; address: string | null; source: string; website_url: string | null; fsq_place_id: string | null; placemaker_url: string | null }>;
type ReferenceStatus = "OFFICIAL_REFERENCE_SUPPORTED" | "OFFICIAL_REFERENCE_CHANNEL_SPECIFIC" | "TEMPORARY_ONLY" | "INSUFFICIENT_EVIDENCE" | "NO_USABLE_REFERENCE";
type ReferenceProfile = Readonly<{ status: ReferenceStatus; sourceUrl: string; sourceType: string; channel: "dine_in" | "pickup" | "official_delivery" | "unspecified_official"; sourceSummary: string; qualifyingItems?: readonly Readonly<{ name: string; amountMinor: number }>[]; excludedItems: readonly string[]; minAmountMinor?: number; maxAmountMinor?: number; freshness: string }>;

const DISCLAIMER = "Based on official brand pricing. Prices may vary by branch or ordering channel.";
const DERIVATION_VERSION = "normal-solo-order-class.v1";

// Amounts below are copied only from the merchant-controlled source URL saved with each profile.
const REFERENCES: Readonly<Record<string, ReferenceProfile>> = {
  Jollibee: { status: "OFFICIAL_REFERENCE_CHANNEL_SPECIFIC", sourceUrl: "https://order.jollibee.com/en/ph", sourceType: "official_ordering_system", channel: "official_delivery", sourceSummary: "Current official ordering menu captured 2026-09-03; it displays normal individual combos alongside family products.", qualifyingItems: [{ name: "Jolly Spaghetti w/ Yumburger w/ Drink", amountMinor: 14_300 }, { name: "Yumburger w/ Fries & Drink", amountMinor: 15_400 }, { name: "1-pc Chickenjoy w/ Burger Steak w/ Drink", amountMinor: 19_400 }, { name: "1-pc Chickenjoy, Half Jolly Spaghetti, Reg. Fries with Rice and Reg. Drink", amountMinor: 20_600 }, { name: "1-pc Chickenjoy, Half Jolly Spaghetti, Burger Steak with Rice and Reg. Drink", amountMinor: 25_000 }], excludedItems: ["free-delivery and gift promos", "family pans", "buckets", "family boxes"], minAmountMinor: 14_300, maxAmountMinor: 25_000, freshness: "fresh; re-capture at most every 90 days and invalidate if the source changes." },
  KFC: { status: "OFFICIAL_REFERENCE_CHANNEL_SPECIFIC", sourceUrl: "https://www.kfc.com.ph/en/menu", sourceType: "official_ordering_system", channel: "unspecified_official", sourceSummary: "Current official menu captured 2026-09-03. The page advertises delivery and pickup but not a declared universal ordering context, so it is not labelled dine-in.", qualifyingItems: [{ name: "1-PC Chicken Meal", amountMinor: 14_000 }, { name: "Chicken Burger Combo", amountMinor: 15_000 }, { name: "1-PC Chicken Meal With Soup", amountMinor: 18_500 }, { name: "Ala King Rice Bowl Meal", amountMinor: 21_000 }, { name: "2-PC Chicken Meal", amountMinor: 24_500 }, { name: "Zinger Burger Combo", amountMinor: 27_000 }], excludedItems: ["what's-new promotions", "buckets", "super platters", "add-ons", "sides", "desserts"], minAmountMinor: 14_000, maxAmountMinor: 27_000, freshness: "fresh; re-capture at most every 90 days and invalidate if the source changes." },
  "Mang Inasal": { status: "OFFICIAL_REFERENCE_SUPPORTED", sourceUrl: "https://www.manginasal.ph/news/menu-and-prices", sourceType: "official_published_menu", channel: "unspecified_official", sourceSummary: "Official 'Menu and Prices 2026', posted 2026-08-01, labels amounts DINE-IN / TAKEOUT. The combined context is retained as unspecified_official rather than recast as delivery.", qualifyingItems: [{ name: "Regular Chicken 1 Rice", amountMinor: 9_900 }, { name: "Paa Large 1 Rice", amountMinor: 13_900 }, { name: "Pork Sisig 1 Rice", amountMinor: 10_500 }, { name: "Pecho Large 1 Rice", amountMinor: 16_900 }, { name: "Paa Large Unli Rice", amountMinor: 17_900 }, { name: "Spicy Pecho Large Unli Rice", amountMinor: 22_400 }, { name: "Spicy Pecho Large Unli Rice Value Meal", amountMinor: 25_500 }], excludedItems: ["buddy/family/party sizes", "solo and family fiesta bundles", "halo-halo-only orders", "promos"], minAmountMinor: 9_900, maxAmountMinor: 25_500, freshness: "dated official menu; re-capture at most every 90 days and expire when superseded." },
  "McDonald's": { status: "INSUFFICIENT_EVIDENCE", sourceUrl: "https://socials.mcdelivery.com.ph/", sourceType: "official_ordering_system", channel: "official_delivery", sourceSummary: "Current official McDelivery was identified, but accessible evidence did not provide a reproducible PHP menu item set for a normal-order range.", excludedItems: ["unverified inaccessible menu amounts"], freshness: "no profile" },
  Starbucks: { status: "INSUFFICIENT_EVIDENCE", sourceUrl: "https://www.starbucks.ph/menu", sourceType: "official_brand_menu", channel: "unspecified_official", sourceSummary: "The official Philippine menu exposes catalogue categories but no accessible current PHP prices; Reserve products remain outside a standard-store profile.", excludedItems: ["Reserve items", "whole beans", "whole cakes", "merchandise", "inaccessible price data"], freshness: "no profile" },
  Chowking: { status: "INSUFFICIENT_EVIDENCE", sourceUrl: "https://order.chowking.ph/", sourceType: "official_ordering_system", channel: "official_delivery", sourceSummary: "An official delivery system is current, but accessible evidence did not yield a representative normal-meal price set; drinks alone are not a food-chain spend profile.", excludedItems: ["drinks-only capture", "promos"], freshness: "no profile" },
  "Pickup Coffee": { status: "INSUFFICIENT_EVIDENCE", sourceUrl: "https://pickup-coffee.com/menu", sourceType: "official_brand_menu", channel: "unspecified_official", sourceSummary: "The official Philippine catalogue identifies beverages but does not expose reproducible current PHP item prices in accessible text.", excludedItems: ["inaccessible price data"], freshness: "no profile" },
  "ZUS Coffee": { status: "INSUFFICIENT_EVIDENCE", sourceUrl: "https://zuscoffee.ph/category/drinks/zus-signature/", sourceType: "official_brand_menu", channel: "unspecified_official", sourceSummary: "The official Philippines catalogue identifies drinks and food categories but no reproducible PHP item prices.", excludedItems: ["app-first-time-user offer", "inaccessible price data"], freshness: "no profile" },
  "Macao Imperial Tea": { status: "NO_USABLE_REFERENCE", sourceUrl: "", sourceType: "none", channel: "unspecified_official", sourceSummary: "No current merchant-controlled Philippine price-bearing menu was located in this pilot.", excludedItems: ["third-party menus", "social posts", "promotions"], freshness: "no profile" },
  Chatime: { status: "INSUFFICIENT_EVIDENCE", sourceUrl: "https://chatime.com.ph/menu2025/", sourceType: "official_brand_menu", channel: "unspecified_official", sourceSummary: "The current official Philippines menu identifies products but does not expose current PHP prices in accessible text.", excludedItems: ["inaccessible price data"], freshness: "no profile" },
  Serenitea: { status: "NO_USABLE_REFERENCE", sourceUrl: "", sourceType: "none", channel: "unspecified_official", sourceSummary: "No current merchant-controlled Philippine price-bearing menu was located in this pilot.", excludedItems: ["third-party menus", "social posts", "promotions"], freshness: "no profile" },
  "CoCo Fresh Tea & Juice": { status: "NO_USABLE_REFERENCE", sourceUrl: "https://cocobubbletea.com/menu/", sourceType: "official_brand_menu", channel: "unspecified_official", sourceSummary: "A global official menu was found, but accessible evidence does not establish a current Philippines price scope.", excludedItems: ["non-Philippines/unknown price scope"], freshness: "no profile" },
  "Army Navy": { status: "NO_USABLE_REFERENCE", sourceUrl: "https://www.armynavy.com.ph/nutrition-facts", sourceType: "official_website", channel: "unspecified_official", sourceSummary: "The official site has current product/nutrition data but no current price-bearing menu in accessible evidence.", excludedItems: ["nutrition-only evidence"], freshness: "no profile" },
};

const candidateNames = Object.keys(REFERENCES);
const profileIsUsable = (profile: ReferenceProfile) => profile.status === "OFFICIAL_REFERENCE_SUPPORTED" || profile.status === "OFFICIAL_REFERENCE_CHANNEL_SPECIFIC";
const exceptionalLocation = (address: string | null) => /\b(airport|reserve|premium)\b/iu.test(address ?? "") ? "Exceptional location marker requires explicit profile opt-out." : null;
const ruleByName = (name: string): ChainIdentityRule => { const rule = PILOT_BRAND_IDENTITY_RULES.find((item) => item.canonicalName === name); if (!rule) throw new Error(`No identity rule for ${name}.`); return rule; };

async function main(): Promise<void> {
  try { loadEnvFile(fileURLToPath(new URL("../../.env.local", import.meta.url))); } catch { /* operator environment is supported */ }
  const db = await connectSupabaseLoaderDatabase();
  try {
    const result = await db.query<BranchRow>(`select p.id as place_id, p.source_place_id, p.name as place_name, p.address, p.source, coalesce(nullif(p.website_url, ''), nullif(st.source_payload->>'website', '')) as website_url, st.source_payload->>'fsq_place_id' as fsq_place_id, st.source_payload->>'placemaker_url' as placemaker_url from public.ew_places p left join public.ew_data_sources ds on ds.code=p.source left join lateral (select source_payload from public.ew_place_import_staging s where s.source_id=ds.id and s.source_place_id=p.source_place_id order by s.created_at desc limit 1) st on true where p.status='active' and p.name=any($1::text[]) order by p.name,p.address nulls last,p.id`, [candidateNames]);
    const branches = result.rows.map((row) => { const rule = ruleByName(row.place_name); const identity = classifyChainIdentity({ rule, sourceWebsiteUrl: row.website_url }); const profile = REFERENCES[rule.canonicalName]!; const optOutReason = exceptionalLocation(row.address); const eligible = identity.status === "CONFIRMED_CHAIN" && profileIsUsable(profile) && !optOutReason; return { place_id: row.place_id, chain: rule.canonicalName, source_place_id: row.source_place_id, place_name: row.place_name, address: row.address, source: row.source, identity_status: identity.status, identity_evidence: { retained_source_website_url: row.website_url, official_domain: identity.host, detail: identity.reason, retained_foursquare_place_id: row.fsq_place_id, placemaker_url: row.placemaker_url }, pricing_profile_applicable: eligible, profile_opt_out_reason: optOutReason, eligibility_reason: eligible ? "Confirmed identity, usable official reference, no exceptional-location marker." : identity.status !== "CONFIRMED_CHAIN" ? "Chain identity is not confirmed." : !profileIsUsable(profile) ? "No usable official chain reference profile." : optOutReason }; });
    const brands = candidateNames.map((name) => { const profile = REFERENCES[name]!; const members = branches.filter((branch) => branch.chain === name); const confirmed = members.filter((branch) => branch.identity_status === "CONFIRMED_CHAIN"); const eligible = members.filter((branch) => branch.pricing_profile_applicable); return { brand_name: name, identity: { expected_official_domains: ruleByName(name).expectedHosts, method: "retained merchant-controlled domain only; exact name is never sufficient" }, reference: { ...profile, pricing_basis: profileIsUsable(profile) ? "brand_reference" : null, currency: profileIsUsable(profile) ? "PHP" : null, pricing_unit: profileIsUsable(profile) ? "per_person" : null, price_precision: profileIsUsable(profile) ? "derived" : null, confidence: profileIsUsable(profile) ? "HIGH" : null, derivation_algorithm_version: profileIsUsable(profile) ? DERIVATION_VERSION : null, reference_disclaimer: profileIsUsable(profile) ? DISCLAIMER : null }, coverage: { active_exact_name_places: members.length, confirmed_places: confirmed.length, eligible_places: eligible.length, opt_out_places: confirmed.filter((branch) => Boolean(branch.profile_opt_out_reason)).length, unresolved_places: members.filter((branch) => branch.identity_status === "UNRESOLVED").length, rejected_places: members.filter((branch) => branch.identity_status === "REJECTED").length, potential_immediate_price_coverage: eligible.length } }; });
    const artifact = { schemaVersion: "explorewise.pricing-reference-pilot.v3", reviewStatus: "pending_human_review", generatedAt: new Date().toISOString(), productionSnapshot: { activePlaces: 25991, placePrices: 1, chains: 0, memberships: 0, casaManilaUnmodified: true }, pricingSemantics: { branch_verified: "Current price verified for this place.", brand_reference: "Current official brand menu reference for a confirmed eligible location; not an exact location-price claim.", place_reference: "Derived normal spend range from this place's official menu; not an exact bill.", unknown: "No usable, fresh price evidence." }, derivation: { version: DERIVATION_VERSION, method: "Fixed reviewed normal-solo-order item classes; exclude family/bulk/catering/merchandise/add-ons/fees/promos and premium-special outliers. The reference range is min/max of that declared set, never the whole menu. Persist every selected item and exclusion.", alternativesReviewed: { percentile_20_80: "Rejected as primary: it can admit wrong product classes.", median_centered: "Rejected: arbitrary spread obscures source items.", item_class_based: "Selected: deterministic, auditable, representative after review." } }, brands, branches, unresolved: branches.filter((branch) => branch.identity_status !== "CONFIRMED_CHAIN"), coverage: { confirmedEligibleBranches: branches.filter((branch) => branch.pricing_profile_applicable).length, projectedGainedPriceCoverage: branches.filter((branch) => branch.pricing_profile_applicable).length } };
    const artifactDirectory = fileURLToPath(new URL("../../.artifacts/price-pilot/", import.meta.url)); const artifactPath = fileURLToPath(new URL("../../.artifacts/price-pilot/phase1-pricing-reference-pilot.json", import.meta.url)); await mkdir(artifactDirectory, { recursive: true }); await writeFile(artifactPath, `${JSON.stringify(artifact, null, 2)}\n`, "utf8"); console.log(JSON.stringify({ artifactPath, reviewedBrands: brands.length, confirmedEligibleBranches: artifact.coverage.confirmedEligibleBranches, productionWrites: 0 }, null, 2));
  } finally { await db.end(); }
}

main().catch((error: unknown) => { console.error(error instanceof Error ? error.message : "Unknown error."); process.exitCode = 1; });
