import { loadEnvFile } from "node:process";
import { fileURLToPath } from "node:url";
import type { Client } from "pg";
import { connectSupabaseLoaderDatabase } from "../database/supabase-loader-client.js";
import { PROMOTE_STAGED_PLACE_SQL } from "../promotion/foursquare-promotion.js";

const SOURCE_ID = "71aad752-1586-459f-9540-7f7c81c12300";
const SOURCE_CODE = "foursquare_os";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
type Candidate = { source_place_id: string; name: string; mapped_category_code: string; country_code: string; region: string | null; city: string | null; district: string | null; address: string | null; longitude: string; latitude: string; timezone: string; currency_code: string; website_url: string | null; phone_number: string | null; source_updated_at: string | null };

function options(args: readonly string[]): { runId: string; dryRun: boolean } {
  const position = args.indexOf("--run-id"); const runId = position < 0 ? undefined : args[position + 1];
  if (!runId || !UUID.test(runId) || args.some((arg) => !["--run-id", runId, "--dry-run"].includes(arg))) throw new Error("Usage: npm run promote:foursquare -- --run-id <uuid> [--dry-run]");
  return { runId, dryRun: args.includes("--dry-run") };
}
function loadEnvironment(): void { try { loadEnvFile(fileURLToPath(new URL("../../.env.local", import.meta.url))); } catch { if (!process.env.SUPABASE_DB_URL?.trim()) throw new Error("SUPABASE_DB_URL is required in tools/ingestion/.env.local or the operator environment."); } }
function flagExpression(): string { return `coalesce(array(select distinct lower(btrim(flag)) from jsonb_array_elements_text(case when jsonb_typeof(s.source_payload -> 'unresolved_flags') = 'array' then s.source_payload -> 'unresolved_flags' else '[]'::jsonb end) flag where btrim(flag) <> '' order by lower(btrim(flag))), array[]::text[])`; }
function classified(runId: string): string { return `with staged as (select s.*, c.id category_id, c.is_active category_active, ${flagExpression()} flags, nullif(btrim(s.source_payload ->> 'date_closed'), '') date_closed_value from public.ew_place_import_staging s left join public.ew_categories c on c.code=s.mapped_category_code where s.ingestion_run_id=$1 and s.source_id='${SOURCE_ID}'), classified as (select *, validation_status='valid' and mapped_category_code is not null and category_id is not null and category_active and cardinality(flags)=0 and date_closed_value is null eligible from staged)`; }
async function preflight(db: Client, runId: string): Promise<Record<string, unknown>> { const result = await db.query(`select r.source_id::text source_id, r.status, r.records_received, r.records_valid, r.records_rejected, count(s.*) rows, count(*) filter(where s.validation_status='valid') valid, count(*) filter(where s.validation_status='review') review, count(*) filter(where s.validation_status='invalid') invalid, count(*) filter(where s.validation_status='valid' and (s.mapped_category_code is null or c.id is null or not c.is_active)) unresolved from public.ew_ingestion_runs r left join public.ew_place_import_staging s on s.ingestion_run_id=r.id left join public.ew_categories c on c.code=s.mapped_category_code where r.id=$1 group by r.id`, [runId]); const row = result.rows[0] as Record<string, unknown> | undefined; if (!row || row.source_id !== SOURCE_ID || row.status !== "completed" || String(row.rows)!==String(row.records_received) || String(row.valid)!==String(row.records_valid) || Number(row.unresolved)!==0) throw new Error("Promotion preflight failed: run is unknown, wrong-source, unreconciled, or lacks resolved persisted category snapshots."); return row; }
async function report(db: Client, runId: string): Promise<unknown> { const result = await db.query(`${classified(runId)} select jsonb_build_object('total',count(*),'eligible',count(*) filter(where eligible),'review',count(*) filter(where validation_status='review'),'invalid',count(*) filter(where validation_status='invalid'),'unresolved_mapped_category',count(*) filter(where validation_status='valid' and (mapped_category_code is null or category_id is null or not category_active)),'duplicate',count(*) filter(where 'duplicate'=any(flags)),'closed',count(*) filter(where 'closed'=any(flags) or date_closed_value is not null),'privatevenue',count(*) filter(where 'privatevenue'=any(flags)),'doesnt_exist_or_unknown',count(*) filter(where exists(select 1 from unnest(flags) f where f not in ('duplicate','closed','privatevenue'))),'missing_required_place_fields',count(*) filter(where eligible and (source_place_id is null or name is null or country_code is null or latitude is null or longitude is null or timezone is null or currency_code is null))) report from classified`, [runId]); return result.rows[0]?.report; }
async function candidates(db: Client, runId: string): Promise<Candidate[]> { const result = await db.query(`${classified(runId)} select source_place_id,name,mapped_category_code,country_code,region,city,district,address,longitude,latitude,timezone,currency_code,website_url,phone_number,source_updated_at from classified where eligible order by source_place_id`, [runId]); return result.rows as Candidate[]; }
async function promote(db: Client, rows: readonly Candidate[]): Promise<Record<string, number>> { const counts={inserted:0,updated:0,unchanged:0,stale:0}; for(const row of rows){ const current=await db.query("select source_updated_at from public.ew_places where source=$1 and source_place_id=$2",[SOURCE_CODE,row.source_place_id]); const existing=current.rows[0]?.source_updated_at as string | null | undefined; if(existing!==undefined && row.source_updated_at===null){counts.unchanged++;continue;} if(existing && row.source_updated_at && Date.parse(row.source_updated_at)<Date.parse(existing)){counts.stale++;continue;} const write=await db.query(PROMOTE_STAGED_PLACE_SQL,[SOURCE_CODE,row.source_place_id,row.name,row.mapped_category_code,row.country_code,row.region,row.city,row.district,row.address,row.longitude,row.latitude,row.timezone,row.currency_code,row.website_url,row.phone_number,row.source_updated_at]); if(write.rowCount===0) counts.unchanged++; else if(existing===undefined) counts.inserted++; else counts.updated++; } return counts; }
async function main(): Promise<void> { const input=options(process.argv.slice(2)); loadEnvironment(); const db=await connectSupabaseLoaderDatabase(); try { const guard=await preflight(db,input.runId); const dryRun=await report(db,input.runId); if(input.dryRun){console.log(JSON.stringify({runId:input.runId,dryRun:true,guard,report:dryRun},null,2));return;} const rows=await candidates(db,input.runId); console.log(JSON.stringify({runId:input.runId,dryRun:false,guard,report:dryRun,results:await promote(db,rows)},null,2)); } finally { await db.end(); } }
main().catch((cause:unknown)=>{console.error(cause instanceof Error?cause.message:"Unknown promotion error.");process.exitCode=1;});
