import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ObservedMerchantAdapter, type MerchantOrderingAdapter, type MerchantSourceManifest } from "../pricing/merchant-ordering.js";

const CAPTURED_AT = "2026-09-03T00:00:00.000Z";
const item = (name: string, amountMinor: number, sourceReference: string, category?: string) => ({ name, amountMinor, currency: "PHP", sourceReference, ...(category ? { category } : {}) });
const adapters: readonly MerchantOrderingAdapter[] = [
  new ObservedMerchantAdapter({ key: "kfc-ph", name: "KFC Philippines", officialDomain: "www.kfc.com.ph", sourceType: "official_ordering_system", sourceReference: "https://www.kfc.com.ph/en/menu", refreshFeasibility: "SEMI_AUTOMATED_REFRESH" }, {
    storeDiscovery: "PARTIALLY_ENUMERABLE", stores: [], warnings: ["Official stores.kfc.com.ph locator is public, but the bounded pilot could not reproducibly extract its dynamic store records without escalating access or probing private endpoints.", "Global menu has no declared store applicability; do not infer branch price."], unsupportedFields: ["external_store_id", "coordinates", "per-store menu applicability", "source update timestamp"],
    menus: [{ applicability: "CHANNEL_MENU", channel: "unspecified_official", capturedAt: CAPTURED_AT, sourceReference: "https://www.kfc.com.ph/en/menu", items: [item("1-PC Chicken Meal", 24_500, "https://www.kfc.com.ph/en/menu", "Favourites"), item("Zinger Burger Combo", 27_000, "https://www.kfc.com.ph/en/menu", "Burgers"), item("Bucket of 6", 59_500, "https://www.kfc.com.ph/en/menu", "Bucket Combos")] }],
  }),
  new ObservedMerchantAdapter({ key: "chowking-ph", name: "Chowking Philippines", officialDomain: "www.chowking.ph", sourceType: "official_store_locator", sourceReference: "https://www.chowking.ph/location", refreshFeasibility: "AUTOMATABLE_REFRESH" }, {
    storeDiscovery: "PARTIALLY_ENUMERABLE", warnings: ["One official locator response returned 15 store records, addresses, phones, hours and services; it did not establish a documented all-store endpoint in the bounded pilot. No stable external store IDs or coordinates were observed.", "Official menu navigation did not expose price-bearing menu items in this bounded public capture; ordering menus require a selected fulfillment location."], unsupportedFields: ["external_store_id", "coordinates", "price-bearing menu", "menu IDs", "item IDs", "source update timestamp"], menus: [],
    stores: [
      ["SM MEGAMALL", "Unit 208 Ground Floor, SM Megamall, Building A, Ortigas Center", "8635-4668 / 9209114913"], ["ANNAPOLIS ALBANY", "Lot1 Block 9 Albany Street, Corner Annapolis Street", "86937017 / 0998-9524339"], ["EDSA CENTRAL", "Shaw Boulevard Corner Sto Cristo Street, Mandaluyong City", "8-252-3963 / 09209114842 / 09453074701"], ["SHAW ACACIA", "Acacia Lane, Shaw Boulevard, Baranggay Addition Hills, Mandaluyong City", "8-355-4378 / 9453196362"], ["SM LIGHT MALL", "Level 1 SM Light Mall, EDSA Corner Madison Street, Barangka", "7-719-9432"], ["SHAW BLVD.", "24 AA Tangco Building, Shaw Boulevard Corner Kalentong Street", "88760928 / 9286153596"], ["BONI AVE.", "599 Boni Avenue Corner Sto. Rosario Street", "84708156 / 9297169330"], ["ROBINSONS GALLERIA", "Level 1 Robinsons Galleria, EDSA Corner Ortigas Avenue", "82779146"], ["STARMALL", "Ground Floor Starmall Building Corner Shaw Boulevard Mandaluyong City", "8-727-8929 / 9202006886"], ["BONNY SERRANO", "Ground Floor & 2F JG Ocampo Building Lot 7B, Blk.4, Col. Bonny Serrano Avenue", "8-470-5042 / 0928-5022362"], ["REMAR", "Level 1-2 Roxanne Building, Aurora Boulevard", "09213395908 / 0920-5406249"], ["EDSA CUBAO", "Level 1 Good Leaf Building, EDSA Street", "09196226464 / 09060653825"], ["SAMPAGUITA (ARANETA CUBAO)", "Sampaguita Theater Building, General Araneta Avenue, Corner General", "8-241-0104 / 0998-8474601"], ["ALI MALL", "Level 1 Ali Mall Building, P. Tuazon Boulevard Corner General", "8-332-5919 / 0998-5686867"], ["HI-TOP", "HiTop Supermarket Building, Aurora Boulevard Corner Castillo Street", "8-421-06-26 / 0920-9114922"],
    ].map(([name, address, phone]) => ({ name: `Chowking ${name!}`, address: address!, phone: phone!, active: true, sourceReference: "https://www.chowking.ph/location" })),
  }),
  new ObservedMerchantAdapter({ key: "jollibee-ph", name: "Jollibee Philippines", officialDomain: "order.jollibee.com", sourceType: "official_ordering_system", sourceReference: "https://order.jollibee.com/en/ph", refreshFeasibility: "SEMI_AUTOMATED_REFRESH" }, {
    storeDiscovery: "PARTIALLY_ENUMERABLE", stores: [], warnings: ["Official order.jollibee.com public flow advertises stores and a menu, but store records require interactive search/location selection in the bounded capture.", "Displayed menu items are official_delivery evidence; no store applicability, item IDs, or store IDs were observed."], unsupportedFields: ["external_store_id", "coordinates", "store address", "phone", "menu ID", "item ID", "source update timestamp"],
    menus: [{ applicability: "CHANNEL_MENU", channel: "official_delivery", capturedAt: CAPTURED_AT, sourceReference: "https://order.jollibee.com/en/ph?showPromo=true", items: [item("Jolly Spaghetti w/ Yumburger w/ Drink", 14_300, "https://order.jollibee.com/en/ph?showPromo=true", "Most Popular"), item("Yumburger w/ Fries & Drink", 15_400, "https://order.jollibee.com/en/ph?showPromo=true", "Most Popular"), item("1-pc. Chickenjoy w/ Burger Steak w/ Drink", 19_400, "https://order.jollibee.com/en/ph?showPromo=true", "Most Popular")] }],
  }),
  new ObservedMerchantAdapter({ key: "yardstick-coffee", name: "Yardstick Coffee", officialDomain: "store.yardstickcoffee.com", sourceType: "structured_storefront", sourceReference: "https://store.yardstickcoffee.com/pages/cafe", refreshFeasibility: "AUTOMATABLE_REFRESH" }, {
    storeDiscovery: "BULK_ENUMERABLE", warnings: ["The Shopify product catalog is retail/e-commerce evidence and is not assumed to equal café menu pricing.", "Café menu links are merchant-published PDFs; their bounded contents were not parsed in this pilot."], unsupportedFields: ["external_store_id", "coordinates", "phone", "café item IDs", "café price applicability", "source update timestamp"],
    stores: [["Legazpi Village", "Universal LMS Building, 106 Esteban Street, Makati, Metro Manila"], ["MOA Square", "MOA Square, 2nd Floor, Pasay, Metro Manila"], ["Opus Mall", "Level 2, Maisonette, Opus Mall, Bridgetowne Blvd., Cor. C5 Road, Ugong Norte, Quezon City"], ["Otaku Room BGC", "Atmos Flagship Store BGC, 3rd Avenue, One Bonifacio High Street, Bonifacio Global City, Taguig"], ["Podium", "G/F, The Podium, Ortigas Center, Mandaluyong, Metro Manila"], ["Rockwell", "Stall 227 Maisonette R2 Level Rockwell Powerplant Mall, Makati City 1224"], ["Salcedo Village", "119 L.P. Leviste Street, Makati, 1227 Metro Manila"], ["SM Aura", "4th Floor, SM Cinema, 26th Street Corner McKinley Parkway Bonifacio Global City, Taguig City"], ["The Corner House", "P. Guevarra, cor Recto, San Juan, 1500 Metro Manila"]].map(([name, address]) => ({ name: `Yardstick ${name!}`, address: address!, active: true, sourceReference: "https://store.yardstickcoffee.com/pages/cafe" })),
    menus: [{ applicability: "GLOBAL_MENU", channel: "official_delivery", capturedAt: CAPTURED_AT, sourceReference: "https://store.yardstickcoffee.com/collections/all", items: [item("Golden Ticket", 80_000, "https://store.yardstickcoffee.com/collections/all", "Coffee beans"), item("Kape Mocha", 33_500, "https://store.yardstickcoffee.com/collections/all", "Coffee")]}],
  }),
];

async function main(): Promise<void> {
  const output = resolve(process.cwd(), ".artifacts/pricing-sources/"); await mkdir(output, { recursive: true });
  const manifests: MerchantSourceManifest[] = adapters.map((adapter) => adapter.collect({ capturedAt: CAPTURED_AT }));
  await Promise.all(manifests.map((manifest) => writeFile(resolve(output, `${manifest.merchant.key}-ordering-manifest.json`), `${JSON.stringify(manifest, null, 2)}\n`, "utf8")));
  console.log(JSON.stringify({ output, manifests: manifests.map((manifest) => ({ merchant: manifest.merchant.name, stores: manifest.stores.length, menus: manifest.menus.length, priceBearingItems: manifest.menus.reduce((total, menu) => total + menu.items.filter((entry) => entry.amountMinor !== undefined).length, 0) })), productionWrites: 0 }, null, 2));
}
main().catch((cause: unknown) => { console.error(cause instanceof Error ? cause.message : "Unknown error"); process.exitCode = 1; });
