import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Ionicons from '@expo/vector-icons/Ionicons';
import * as Location from 'expo-location';
import { useRouter } from 'expo-router';
import { Alert, FlatList, Linking, Pressable, ScrollView, StyleSheet, useWindowDimensions, View, type ViewToken } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AskWiseCard } from '@/components/ask-wise-card';
import { LocationSearchSheet } from '@/components/discovery/location-search-sheet';
import { PriceSummary } from '@/components/discovery/price-summary';
import { StateCard } from '@/components/discovery/state-card';
import { ItineraryMap } from '@/components/itinerary/itinerary-map';
import { StartOverAction } from '@/components/itinerary/start-over-action';
import { BudgetSummaryCard, ItineraryStopCard, StageProgress } from '@/components/itinerary/itinerary-ui';
import { ThemedText } from '@/components/themed-text';
import { ClaySurface, LoadingCard, PrimaryButton, SecondaryButton } from '@/components/ui/clay';
import { WiseProposalCard } from '@/components/wise-proposal-card';
import { MaxContentWidth, Spacing, Typography } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { useCurrentLocation } from '@/providers/current-location-provider';
import { usePlanningAlternatives } from '@/providers/planning-alternatives-provider';
import { usePlanningHandoff } from '@/providers/planning-handoff-provider';
import { parseAskWise, type AskWiseIntent } from '@/services/ask-wise';
import { customizeNavigation, originSuggestionLabel, stageSelectionHeading } from '@/services/customize-ui';
import { buildFoodCandidatePool, CUSTOMIZE_CANDIDATE_LIMIT, foodFocusLabel, isFoodStage, orderStageCandidates, shortlistWithSelectedCandidate, stageRankingContextFromIntent, STAGE_CANDIDATE_POOL_LIMIT } from '@/services/food-candidate-diversity';
import { ADD_STOP_CATEGORIES, addUserStage, areRequiredStagesComplete, canNavigate, filterCandidatesForStage, finalizeItinerary, isPlaceAvailableForStage, mapStops, MAX_ITINERARY_STOPS, navigationUrl, remainingBudget, removeUserStage, selectStop, selectedPlaceExclusionKey, stageActivityFocus, stageIndexAfterRemoval, stageOrigin, stageOriginKey, type AddStopCategoryId, type ItineraryState } from '@/services/itinerary';
import { resolvePlanLocation } from '@/services/plan-location';
import { emptyPlanningSession, START_OVER_MESSAGE, START_OVER_TITLE, startOverConfirmation } from '@/services/planning-session';
import { fetchPlanningNearbyPlaces, fetchPricedNearbyPlaces, type PricedNearbyPlace } from '@/services/places';
import { sequentialStopDistances, stageDistanceLabel, stageDistanceOrigin, type StageDistanceOrigin } from '@/services/planning-distance';
import { canCommitGuidedSelection, guidedSelectionTransition } from '@/services/guided-selection';
import { logWiseBudget } from '@/services/wise-budget-diagnostics';
import { logFoodPipeline } from '@/services/wise-food-diagnostics';
import { buildWiseProposal, type WiseProposal } from '@/services/wise-proposal';

type Screen = 'initial' | 'proposal' | 'guided' | 'review' | 'finalized' | 'add-category';
type CarouselItem = Readonly<{ kind: 'place'; place: PricedNearbyPlace }> | Readonly<{ kind: 'more' }>;

export default function PlanScreen() {
  const location = useCurrentLocation(); const theme = useTheme(); const router = useRouter();
  const { pendingWiseRequest, consumePendingWiseRequest } = usePlanningHandoff(); const { openAlternatives, clearAlternatives } = usePlanningAlternatives();
  const [prompt, setPrompt] = useState(''); const [activeRequest, setActiveRequest] = useState<string | null>(null); const [screen, setScreen] = useState<Screen>('initial'); const [proposal, setProposal] = useState<WiseProposal | null>(null); const [state, setState] = useState<ItineraryState | null>(null); const [stageIndex, setStageIndex] = useState(0); const [candidatePool, setCandidatePool] = useState<PricedNearbyPlace[]>([]); const [candidateStageKey, setCandidateStageKey] = useState<string | null>(null); const [highlightedId, setHighlightedId] = useState<string | null>(null); const [selectionTransition, setSelectionTransition] = useState<Readonly<{ stageId: string; placeName: string; returnToReview: boolean }> | null>(null); const [candidateRefreshKey, setCandidateRefreshKey] = useState(0); const [loading, setLoading] = useState(false); const [loadingLabel, setLoadingLabel] = useState(''); const [locationSearchVisible, setLocationSearchVisible] = useState(false); const [error, setError] = useState<string | null>(null); const [history, setHistory] = useState<string[]>([]); const [notice, setNotice] = useState<string | null>(null);
  const autoSubmittedRequestIds = useRef(new Set<string>());
  const addingStopRef = useRef(false);
  const selectionTransitionRef = useRef(false);
  const currentStage = state?.stages[stageIndex];
  const origin = useMemo(() => state ? stageOrigin(state, stageIndex) : null, [stageIndex, state]);
  const currentCandidateKey = currentStage && origin && state ? `${currentStage.id}:${stageOriginKey(state, stageIndex)}:${origin.latitude}:${origin.longitude}:${selectedPlaceExclusionKey(state, currentStage.id)}` : null;
  useEffect(() => { if ((screen === 'review' || screen === 'finalized') && state) logWiseBudget('review', state.budgetMinor); }, [screen, state]);
  useEffect(() => { if (screen !== 'add-category') addingStopRef.current = false; }, [screen]);
  useEffect(() => { if (screen === 'initial') { selectionTransitionRef.current = false; setSelectionTransition(null); } }, [screen]);
  useEffect(() => {
    if (!selectionTransition || !state) return;
    const transition = setTimeout(() => {
      selectionTransitionRef.current = false;
      const selectedIndex = state.stages.findIndex((stage) => stage.id === selectionTransition.stageId);
      setSelectionTransition(null);
      const next = guidedSelectionTransition(selectedIndex, state.stages.length, selectionTransition.returnToReview);
      if (next.kind === 'review') setScreen('review'); else setStageIndex(next.stageIndex);
    }, 380);
    return () => clearTimeout(transition);
  }, [selectionTransition, state]);
  const resolveExplicitLocation = async (query: string) => { const result = (await Location.geocodeAsync(query))[0]; return result && Number.isFinite(result.latitude) && Number.isFinite(result.longitude) ? { coordinates: { latitude: result.latitude, longitude: result.longitude }, label: query, source: 'location-search' as const } : null; };
  const fetchProposal = useCallback(async (intent: AskWiseIntent, previous = history) => {
    setLoading(true); setLoadingLabel('Resolving your location…'); setError(null); setNotice(null);
    const resolved = await resolvePlanLocation({ explicitLocation: intent.location, currentLocation: location.selection, requestCurrentLocation: location.requestCurrentLocation, resolveExplicitLocation }).catch(() => ({ selection: null, reason: 'unavailable' as const }));
    if (!resolved.selection) { setLoading(false); setLoadingLabel(''); setError(resolved.reason === 'explicit-unavailable' ? 'We couldn’t find ' + intent.location + '. Choose another location to continue.' : 'Wise needs your location to build this plan.'); return; }
    setLoadingLabel('Building your plan…');
    try { const next = await buildWiseProposal({ intent, start: { ...resolved.selection.coordinates, label: resolved.selection.label }, excludedCombinations: previous.flatMap((key) => key.split('|')), fetcher: (input) => isFoodStage(input.categoryCodes) ? fetchPlanningNearbyPlaces({ ...input, radiusMeters: 5000, resultLimit: STAGE_CANDIDATE_POOL_LIMIT, foodFocus: intent.foodFocus }) : fetchPricedNearbyPlaces({ ...input, radiusMeters: 5000, resultLimit: 30 }) }); logWiseBudget('proposal', next.state.budgetMinor); setProposal(next); setState(next.state); setScreen('proposal'); } catch { setError('We couldn’t build a grounded plan right now. You can still explore places manually.'); } finally { setLoading(false); setLoadingLabel(''); }
  }, [history, location.requestCurrentLocation, location.selection]);
  const begin = useCallback(async (submittedPrompt = prompt) => {
    const exactPrompt = submittedPrompt.trim(); if (loading || !exactPrompt) return;
    setHistory([]); setProposal(null); setLoading(true); setLoadingLabel('Understanding your plan…'); setError(null);
    const intent = await parseAskWise(exactPrompt).catch(() => null);
    if (!intent) { setLoading(false); setLoadingLabel(''); setError('Ask Wise isn’t available right now. You can still explore places manually.'); return; }
    setActiveRequest(exactPrompt); await fetchProposal(intent, []);
  }, [fetchProposal, loading, prompt]);
  useEffect(() => {
    if (!pendingWiseRequest || autoSubmittedRequestIds.current.has(pendingWiseRequest.id)) return;
    const request = consumePendingWiseRequest(pendingWiseRequest.id); if (!request) return;
    autoSubmittedRequestIds.current.add(request.id); setPrompt(request.prompt); void begin(request.prompt);
  }, [begin, consumePendingWiseRequest, pendingWiseRequest]);
  const tryAnother = async () => { if (!proposal) return; const nextHistory = [...history, proposal.historyKey]; setHistory(nextHistory); await fetchProposal(proposal.intent, nextHistory); };
  useEffect(() => {
    if (screen !== 'guided' || !state || !currentStage || !origin) return;
    let active = true; setLoading(true); setError(null); setCandidateStageKey(null); setCandidatePool([]); setHighlightedId(null); const remaining = remainingBudget(state); const budgetMinor = proposal?.intent.budgetMinor === null ? null : remaining.conservativeMinor ?? state.budgetMinor;
    const rankingContext = stageRankingContextFromIntent(proposal?.intent, stageActivityFocus(currentStage));
    const request = isFoodStage(currentStage.categoryCodes)
      ? fetchPlanningNearbyPlaces({ coordinates: origin, radiusMeters: 5000, categoryCodes: [...currentStage.categoryCodes], resultLimit: STAGE_CANDIDATE_POOL_LIMIT, budgetMinor, partySize: state.partySize, foodFocus: proposal?.intent.foodFocus })
      : fetchPricedNearbyPlaces({ coordinates: origin, radiusMeters: 5000, categoryCodes: [...currentStage.categoryCodes], resultLimit: STAGE_CANDIDATE_POOL_LIMIT, budgetMinor, partySize: state.partySize });
    void request.then((result) => {
      if (!active) return; const eligible = filterCandidatesForStage(state, currentStage.id, result); const ranked = orderStageCandidates(currentStage.categoryCodes, eligible, rankingContext); if (isFoodStage(currentStage.categoryCodes)) logFoodPipeline(currentStage.id, result, eligible, rankingContext); setCandidatePool(ranked); setCandidateStageKey(currentCandidateKey);
      const selected = state.stops.find((stop) => stop.stageId === currentStage.id)?.place.place_id; setHighlightedId(selected ?? ranked[0]?.place_id ?? null);
    }).catch(() => active && setError('We couldn’t load suggestions right now. Try again in a moment.')).finally(() => active && setLoading(false));
    return () => { active = false; };
  // A current-stage selection changes the next stage's origin, not this request.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [candidateRefreshKey, currentCandidateKey, currentStage, proposal?.intent.activityFocus, proposal?.intent.budgetMinor, proposal?.intent.explicitQuickService, proposal?.intent.foodFocus, proposal?.intent.outingContext, screen, state?.partySize]);
  const updateStop = (place: PricedNearbyPlace, returnAddedStopToReview = false) => {
    if (!currentStage || !state || !isPlaceAvailableForStage(state, currentStage.id, place.place_id) || !canCommitGuidedSelection(selectionTransitionRef.current)) return;
    selectionTransitionRef.current = true;
    setState((current) => current ? selectStop(current, currentStage.id, place) : current);
    setCandidatePool((current) => current.some((item) => item.place_id === place.place_id) ? current : [place, ...current]); setHighlightedId(place.place_id);
    setSelectionTransition({ stageId: currentStage.id, placeName: place.name, returnToReview: returnAddedStopToReview && currentStage.source === 'user_added' });
  };
  const openStage = (stageId: string) => { if (!state) return; const index = state.stages.findIndex((stage) => stage.id === stageId); if (index < 0) return; setStageIndex(index); setCandidatePool([]); setHighlightedId(null); setCandidateRefreshKey((key) => key + 1); setScreen('guided'); };
  const removeAddedStage = (stageId: string) => { const removedIndex = state?.stages.findIndex((stage) => stage.id === stageId) ?? -1; const remainingCount = Math.max(0, (state?.stages.length ?? 0) - 1); setState((current) => current ? removeUserStage(current, stageId) : current); if (removedIndex >= 0) setStageIndex((index) => stageIndexAfterRemoval(index, removedIndex, remainingCount)); setCandidatePool([]); setCandidateStageKey(null); setHighlightedId(null); setCandidateRefreshKey((key) => key + 1); if (screen !== 'guided') setScreen('review'); };
  const chooseAddedCategory = (categoryId: AddStopCategoryId) => { if (!state || state.stages.length >= MAX_ITINERARY_STOPS || addingStopRef.current) return; addingStopRef.current = true; const nextIndex = state.stages.length; setState((current) => current ? addUserStage(current, categoryId) : current); setStageIndex(nextIndex); setCandidatePool([]); setCandidateStageKey(null); setHighlightedId(null); setCandidateRefreshKey((key) => key + 1); setScreen('guided'); };
  const clearPlan = () => Alert.alert(START_OVER_TITLE, START_OVER_MESSAGE, startOverConfirmation(() => { const cleared = emptyPlanningSession(); clearAlternatives(); setProposal(null); setState(null); setHistory(cleared.history); setCandidatePool([]); setHighlightedId(null); setStageIndex(0); setNotice(null); setError(null); setActiveRequest(null); setPrompt(''); setScreen(cleared.phase); }));
  const locationError = error === 'Wise needs your location to build this plan.' || error?.startsWith('We couldn’t find');
  if (screen === 'initial') return <Shell theme={theme}><Heading eyebrow="PLAN AN OUTING" title="Make the pieces work." subtitle="Wise understands your request; ExploreWise selects real places." /><AskWiseCard prompt={prompt} onChangePrompt={setPrompt} onSubmit={() => void begin()} isLoading={loading} />{loading ? <LoadingCard label={loadingLabel} /> : null}{error ? locationError ? <><StateCard title="Wise needs your location to build this plan." message={error} actionLabel="Use my location" onAction={() => void begin()} /><SecondaryButton label="Choose location" onPress={() => setLocationSearchVisible(true)} /></> : <StateCard title="Ask Wise is unavailable" message={error} actionLabel="Try again" onAction={() => void begin()} /> : null}<ClaySurface elevation="subtle" style={styles.manual}><ThemedText style={Typography.cardTitle}>Prefer to browse?</ThemedText><ThemedText type="small" themeColor="textSecondary">Explore places manually anytime — planning never blocks discovery.</ThemedText></ClaySurface><LocationSearchSheet visible={locationSearchVisible} onClose={() => setLocationSearchVisible(false)} onUseCurrentLocation={() => { setLocationSearchVisible(false); void begin(); }} /></Shell>;
  if (screen === 'proposal' && proposal) return <Shell theme={theme}><Heading eyebrow="ASK WISE" title="A grounded plan, ready to shape." subtitle="Real place records and price evidence only." />{loading ? <LoadingCard label={loadingLabel} /> : <WiseProposalCard proposal={proposal} requestText={activeRequest} busy={loading} onUse={() => { logWiseBudget('itinerary', proposal.state.budgetMinor); setState(proposal.state); setScreen('review'); }} onCustomize={() => { setState(proposal.state); setStageIndex(0); setCandidateRefreshKey((key) => key + 1); setScreen('guided'); }} onTryAnother={() => void tryAnother()} onStartOver={clearPlan} />}{error ? <StateCard title="Plan unavailable" message={error} /> : null}</Shell>;
  if (!state) return null;
  if (screen === 'add-category') return <Shell theme={theme}><Heading eyebrow="ADD A STOP" title="What do you want to add?" subtitle="Choose a category and we’ll find grounded nearby options from your latest stop." /><View style={styles.categoryChoices}>{ADD_STOP_CATEGORIES.map((category) => <SecondaryButton key={category.id} label={category.label} accessibilityLabel={'Add ' + category.label + ' stop'} onPress={() => chooseAddedCategory(category.id)} />)}</View><SecondaryButton label="Back" onPress={() => setScreen('review')} /></Shell>;
  if (screen === 'guided') {
    if (selectionTransition && currentStage?.id === selectionTransition.stageId) return <Shell theme={theme}><Heading eyebrow="CUSTOMIZE YOUR PLAN" title="Customize your plan" subtitle={originSuggestionLabel(origin) ?? ''} /><StageProgress state={state} stageIndex={stageIndex} /><BudgetSummaryCard state={state} /><ClaySurface elevation="raised" style={styles.manual} accessibilityLiveRegion="polite"><Ionicons name="checkmark-circle" size={28} color={theme.accent} /><ThemedText style={Typography.cardTitle}>{selectionTransition.placeName} selected</ThemedText><ThemedText type="small" themeColor="textSecondary">Loading the next step…</ThemedText></ClaySurface><View style={styles.stageActions}><SecondaryButton label="Back" disabled={stageIndex === 0} onPress={() => { selectionTransitionRef.current = false; setSelectionTransition(null); setStageIndex((index) => Math.max(0, index - 1)); }} style={styles.flex} /></View><StartOverAction onPress={clearPlan} /></Shell>;
    if (error) return <Shell theme={theme}><Heading eyebrow="CUSTOMIZE YOUR PLAN" title="Customize your plan" subtitle={originSuggestionLabel(origin) ?? ''} /><StageProgress state={state} stageIndex={stageIndex} /><StateCard title="Suggestions unavailable" message="We couldn’t load suggestions for this stop. Your existing plan is still intact." actionLabel="Retry" onAction={() => setCandidateRefreshKey((key) => key + 1)} /><View style={styles.stageActions}><SecondaryButton label="Back" disabled={stageIndex === 0} onPress={() => setStageIndex((index) => Math.max(0, index - 1))} style={styles.flex} /></View><StartOverAction onPress={clearPlan} /></Shell>;
    if (!loading && currentStage && candidateStageKey === currentCandidateKey && candidatePool.length === 0) return <Shell theme={theme}><Heading eyebrow="CUSTOMIZE YOUR PLAN" title="Customize your plan" subtitle={originSuggestionLabel(origin) ?? ''} /><StageProgress state={state} stageIndex={stageIndex} /><StateCard title="No good matches found for this stop." message="Try again or change this stage of your plan." actionLabel="Retry" onAction={() => setCandidateRefreshKey((key) => key + 1)} />{currentStage.source === 'user_added' ? <SecondaryButton label="Remove stop" onPress={() => removeAddedStage(currentStage.id)} /> : null}<View style={styles.stageActions}><SecondaryButton label="Back" disabled={stageIndex === 0} onPress={() => setStageIndex((index) => Math.max(0, index - 1))} style={styles.flex} /><PrimaryButton label={stageIndex === state.stages.length - 1 ? 'Review your plan' : 'Next'} disabled style={styles.flex} /></View><StartOverAction onPress={clearPlan} /></Shell>;
    const selectedId = currentStage ? state.stops.find((stop) => stop.stageId === currentStage.id)?.place.place_id ?? null : null;
    const currentSelectionValid = Boolean(selectedId && candidateStageKey === currentCandidateKey && candidatePool.some((candidate) => candidate.place_id === selectedId));
    const navigation = customizeNavigation(state, stageIndex, { loading, currentSelectionValid });
    const rankingContext = stageRankingContextFromIntent(proposal?.intent, currentStage ? stageActivityFocus(currentStage) : null);
    const foodPool = currentStage && isFoodStage(currentStage.categoryCodes) ? buildFoodCandidatePool(candidatePool, rankingContext) : null;
    const shortlist = currentStage ? shortlistWithSelectedCandidate(currentStage.categoryCodes, candidatePool, selectedId, CUSTOMIZE_CANDIDATE_LIMIT, rankingContext) : [];
    const shortlistIds = shortlist.map((place) => place.place_id);
    const distanceOrigin = stageDistanceOrigin(state, stageIndex);
    const viewMore = () => { if (!proposal || !currentStage || !origin) return; openAlternatives({ proposal, state, stage: currentStage, stageIndex, origin, distanceOrigin, candidates: candidatePool, shortlistedIds: shortlistIds, broaderCandidateIds: foodPool?.broader.map((place) => place.place_id) ?? [], explicitFoodFocus: foodPool?.explicitFocus ?? null, selectedId, select: (place) => { updateStop(place); router.back(); } }); router.push('/plan/alternatives' as never); };
    const explicitNoMatch = foodPool?.mode === 'explicit_food_no_match' ? foodPool.explicitFocus : null;
    return <Shell theme={theme}><Heading eyebrow="CUSTOMIZE YOUR PLAN" title="Customize your plan" subtitle={originSuggestionLabel(origin) ?? ''} /><StageProgress state={state} stageIndex={stageIndex} /><BudgetSummaryCard state={state} />{loading ? <LoadingCard label="Matching real places for this stage…" /> : explicitNoMatch ? <><StateCard title={`No strong ${foodFocusLabel(explicitNoMatch)} matches found nearby.`} message="Broader food alternatives are available, but they do not satisfy the explicit request." actionLabel={foodPool?.broader.length ? 'View more options' : undefined} onAction={foodPool?.broader.length ? viewMore : undefined} />{shortlist.length && currentStage ? <CandidateList title="Selected broader alternative" candidates={shortlist} distanceOrigin={distanceOrigin} hasMoreOptions={candidatePool.length > shortlist.length} highlightedId={highlightedId} selectedId={selectedId} onHighlight={setHighlightedId} onSelect={(place) => updateStop(place, currentStage.source === 'user_added')} onViewMore={viewMore} /> : null}</> : currentStage ? <CandidateList title={stageSelectionHeading(currentStage)} candidates={shortlist} distanceOrigin={distanceOrigin} hasMoreOptions={candidatePool.length > shortlist.length} highlightedId={highlightedId} selectedId={selectedId} onHighlight={setHighlightedId} onSelect={(place) => updateStop(place, currentStage.source === 'user_added')} onViewMore={viewMore} /> : null}{currentStage?.source === 'user_added' && selectedId ? <SecondaryButton label="Remove stop" accessibilityLabel={'Remove ' + currentStage.title + ' stop'} onPress={() => removeAddedStage(currentStage.id)} /> : null}<View style={styles.stageActions}><SecondaryButton label="Back" accessibilityLabel="Back to previous Customize stage" disabled={navigation.backDisabled} onPress={() => setStageIndex((index) => Math.max(0, index - 1))} style={styles.flex} /><PrimaryButton label={navigation.primaryLabel} accessibilityLabel={navigation.primaryLabel} disabled={!navigation.canContinue} onPress={() => navigation.review ? setScreen('review') : setStageIndex((index) => index + 1)} style={styles.flex} /></View><StartOverAction onPress={clearPlan} /></Shell>;
  }
  const complete = areRequiredStagesComplete(state); const first = mapStops(state)[0]?.place; const editable = screen === 'review' && !state.finalized; const canAdd = editable && state.stages.length < MAX_ITINERARY_STOPS;
  return <Shell theme={theme}><Heading eyebrow={screen === 'finalized' ? 'ITINERARY FINALIZED' : 'REVIEW YOUR PLAN'} title={screen === 'finalized' ? 'Your plan is ready.' : 'Check the details.'} subtitle={notice ?? (editable ? 'Edit any stop before you finalize.' : 'Your selected stops are ready for navigation.')} /><BudgetSummaryCard state={state} /><ClaySurface style={styles.mapSurface}><ItineraryMap start={state.start} candidates={[]} selected={state.stops.map((stop) => stop.place)} highlightedId={null} onPressCandidate={() => {}} /></ClaySurface><SelectedStops state={state} editable={editable} onRemoveAdded={removeAddedStage} onReplace={openStage} />{canAdd ? <SecondaryButton label="+ Add another stop" accessibilityLabel="Add another stop" onPress={() => setScreen('add-category')} /> : editable ? <ThemedText type="small" themeColor="textSecondary">Maximum of {MAX_ITINERARY_STOPS} stops reached. Remove a manually added stop to add another.</ThemedText> : null}{!complete ? <ThemedText type="small" themeColor="textSecondary">Required stages are incomplete. Add the missing stops before finalizing.</ThemedText> : editable ? <PrimaryButton label="Finalize itinerary" onPress={() => { setState((current) => current ? finalizeItinerary(current) : current); setScreen('finalized'); setNotice('Your itinerary is finalized. Navigation is ready for the first stop.'); }} /> : state.finalized && canNavigate('finalized') && first ? <PrimaryButton label="Navigate to first stop" onPress={() => void Linking.openURL(navigationUrl(first))} /> : null}<View style={styles.actions}>{editable ? <SecondaryButton label="Customize" onPress={() => { setStageIndex(0); setScreen('guided'); }} /> : null}<StartOverAction onPress={clearPlan} /></View></Shell>;
}

function Shell({ children, theme }: { children: React.ReactNode; theme: ReturnType<typeof useTheme> }) { return <View style={[styles.screen, { backgroundColor: theme.background }]}><SafeAreaView edges={['top']} style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>{children}</ScrollView></SafeAreaView></View>; }
function Heading({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <View style={styles.heading}><ThemedText type="smallBold" themeColor="textSecondary" style={styles.eyebrow}>{eyebrow}</ThemedText><ThemedText style={Typography.screenHeading}>{title}</ThemedText>{subtitle ? <ThemedText type="small" themeColor="textSecondary">{subtitle}</ThemedText> : null}</View>; }
function CandidateList({ title, candidates, distanceOrigin, hasMoreOptions, highlightedId, selectedId, onHighlight, onSelect, onViewMore }: { title: string; candidates: PricedNearbyPlace[]; distanceOrigin: StageDistanceOrigin; hasMoreOptions: boolean; highlightedId: string | null; selectedId: string | null; onHighlight: (id: string) => void; onSelect: (place: PricedNearbyPlace) => void; onViewMore: () => void }) {
  const theme = useTheme(); const listRef = useRef<FlatList<CarouselItem>>(null); const { width } = useWindowDimensions(); const cardWidth = Math.floor(Math.max(1, width - Spacing.md * 2) * 0.86); const snapInterval = cardWidth + Spacing.sm; const [focusedIndex, setFocusedIndex] = useState(0);
  const items = useMemo<CarouselItem[]>(() => [...candidates.map((place) => ({ kind: 'place' as const, place })), ...(hasMoreOptions ? [{ kind: 'more' as const }] : [])], [candidates, hasMoreOptions]);
  const selectedIndex = candidates.findIndex((place) => place.place_id === selectedId);
  const snapToSelected = useCallback(() => { if (selectedIndex >= 0) { setFocusedIndex(selectedIndex); listRef.current?.scrollToIndex({ animated: true, index: selectedIndex, viewPosition: 0 }); } }, [selectedIndex]);
  const onViewableItemsChanged = useCallback(({ viewableItems }: { viewableItems: ViewToken[] }) => { const focused = viewableItems.find((item) => item.isViewable && item.index !== null); if (focused?.index === null || focused?.index === undefined) return; setFocusedIndex(focused.index); const item = items[focused.index]; if (item?.kind === 'place') onHighlight(item.place.place_id); }, [items, onHighlight]);
  useEffect(() => { snapToSelected(); }, [snapToSelected]);
  if (!candidates.length) return <StateCard title="No matching places yet" message="Try another location or adjust this stage of your plan." />;
  return <View style={styles.candidateSection} accessibilityLabel={title + ', ' + Math.min(focusedIndex + 1, candidates.length) + ' of ' + candidates.length}><ThemedText style={Typography.cardTitle}>{title}</ThemedText><FlatList ref={listRef} horizontal data={items} keyExtractor={(item) => item.kind === 'place' ? item.place.place_id : 'view-more-options'} renderItem={({ item, index }) => item.kind === 'more' ? <ClaySurface elevation="raised" style={[styles.candidate, { width: cardWidth }]}><View style={styles.candidateCopy}><Ionicons name="sparkles-outline" size={25} color={theme.accent} /><ThemedText style={Typography.cardTitle}>View more options</ThemedText><ThemedText type="small" themeColor="textSecondary">Browse more eligible places without changing your plan.</ThemedText></View><PrimaryButton label="View more options" accessibilityLabel="View more options" onPress={onViewMore} /></ClaySurface> : <ClaySurface elevation={highlightedId === item.place.place_id ? 'raised' : 'card'} style={[styles.candidate, { width: cardWidth }]}><Pressable accessibilityRole="button" accessibilityLabel={'Candidate ' + (index + 1) + ' of ' + candidates.length + ': ' + item.place.name + (selectedId === item.place.place_id ? ', currently selected' : '')} accessibilityState={{ selected: selectedId === item.place.place_id }} onPress={() => onHighlight(item.place.place_id)} style={styles.candidateCopy}><ThemedText style={Typography.cardTitle}>{item.place.name}</ThemedText>{item.place.category_name || item.place.category_code ? <ThemedText type="small" themeColor="textSecondary">{item.place.category_name ?? item.place.category_code}</ThemedText> : null}{stageDistanceLabel(distanceOrigin, item.place) ? <ThemedText type="small" themeColor="textSecondary">{stageDistanceLabel(distanceOrigin, item.place)}</ThemedText> : null}<PriceSummary place={item.place} />{selectedId === item.place.place_id ? <ThemedText type="smallBold" themeColor="textSecondary">Selected</ThemedText> : null}</Pressable><PrimaryButton label={selectedId === item.place.place_id ? 'Selected' : 'Select this stop'} accessibilityLabel={'Select ' + item.place.name + ' for this stop'} onPress={() => onSelect(item.place)} /></ClaySurface>} showsHorizontalScrollIndicator={false} snapToAlignment="start" snapToInterval={snapInterval} disableIntervalMomentum decelerationRate="fast" contentContainerStyle={styles.carouselContent} onContentSizeChange={snapToSelected} onViewableItemsChanged={onViewableItemsChanged} viewabilityConfig={{ itemVisiblePercentThreshold: 60 }} onScrollToIndexFailed={({ index }) => { listRef.current?.scrollToOffset({ animated: true, offset: index * snapInterval }); requestAnimationFrame(snapToSelected); }} /><ThemedText type="smallBold" themeColor="textSecondary" accessibilityLiveRegion="polite">{focusedIndex + 1} of {candidates.length}</ThemedText></View>;
}
function SelectedStops({ state, editable, onRemoveAdded, onReplace }: { state: ItineraryState; editable: boolean; onRemoveAdded: (id: string) => void; onReplace: (id: string) => void }) { const distances = sequentialStopDistances(state); return <View style={styles.candidates}>{mapStops(state).map(({ place, number, stageId }, index) => { const stage = state.stages.find((item) => item.id === stageId); return <View key={stageId} style={styles.candidates}><ItineraryStopCard place={place} number={number} distanceLabel={distances[index]?.label} onRemove={editable && stage?.source === 'user_added' ? () => onRemoveAdded(stageId) : undefined} />{editable ? <SecondaryButton label={stage?.source === 'user_added' ? 'Change ' + place.name : 'Replace ' + place.name} onPress={() => onReplace(stageId)} /> : null}</View>; })}</View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, safe: { flex: 1 }, content: { alignSelf: 'center', gap: Spacing.lg, maxWidth: MaxContentWidth, paddingBottom: Spacing.six, paddingHorizontal: Spacing.md, paddingTop: Spacing.md, width: '100%' }, heading: { gap: Spacing.xs }, eyebrow: { fontSize: 11, letterSpacing: 1.1 }, manual: { gap: Spacing.xs }, mapSurface: { padding: Spacing.sm }, candidates: { gap: Spacing.sm }, candidateSection: { gap: Spacing.sm }, carouselContent: { paddingRight: Spacing.md }, candidate: { gap: Spacing.sm, marginRight: Spacing.sm }, candidateCopy: { gap: Spacing.xs, minHeight: 138 }, actions: { gap: Spacing.sm }, stageActions: { flexDirection: 'row', gap: Spacing.sm }, flex: { flex: 1 }, categoryChoices: { gap: Spacing.sm } });
